version: "3"
networks:
  test-network:
    external: true

services:
  memcached:
    image: memcached:1.5.16
    container_name: test_memcached
    ports:
      - 11211:11211
    networks:
      - test-network
  redis:
    image: redis:5.0.5
    container_name: test_redis
    ports:
      - 6379:6379
    networks:
      - test-network